# Generated by Django 4.2.5 on 2023-09-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0005_emailaddress_idx_upper_email'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('training', '0004_alter_exercises_description'),
        ('socialaccount', '0005_socialtoken_nullable_app'),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
