# Generated by Django 4.2.5 on 2023-10-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userprofile_options_alter_usertraining_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertraining',
            name='title',
            field=models.CharField(default='', max_length=155, verbose_name='Nome do Treino'),
        ),
    ]
