# Generated by Django 4.2.5 on 2023-10-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_alter_exercises_created_at'),
        ('users', '0014_usertraining_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertraining',
            name='exercises',
            field=models.ManyToManyField(blank=True, default='', limit_choices_to={'is_published': True}, to='training.exercises', verbose_name='Exercícios'),
        ),
    ]
