# Generated by Django 4.2.5 on 2023-10-16 13:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0009_alter_exercises_created_at'),
        ('users', '0015_alter_usertraining_exercises'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTraining',
            new_name='UserWorkouts',
        ),
    ]
