# Generated by Django 4.2.5 on 2023-10-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_usertraining_userworkouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkouts',
            name='exercises_total',
            field=models.IntegerField(default=0, verbose_name='Total de Exercícios'),
        ),
    ]
