# Generated by Django 4.2.5 on 2023-11-29 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_userworkouts_exercises_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notifications_total',
            field=models.IntegerField(default=0, verbose_name='Notificações não Vistas'),
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=155, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('send_by', models.CharField(max_length=155, verbose_name='Enviado por')),
                ('send_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('user_saw', models.BooleanField(verbose_name='Usuário Viu')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Enviado para')),
            ],
        ),
    ]
