# Generated by Django 4.2.5 on 2023-11-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userprofile_notifications_total_usernotifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotifications',
            options={'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
    ]
