# Generated by Django 4.2.5 on 2023-12-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_usernotifications_subject_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotifications',
            name='user_saw',
        ),
    ]
