# Generated by Django 4.2.5 on 2024-01-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_userworkouts_is_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkouts',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='Compartilhado'),
        ),
    ]
