# Generated by Django 4.2.5 on 2024-01-24 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_userworkouts_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AddField(
            model_name='userworkouts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
    ]
