# Generated by Django 4.2.5 on 2024-01-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_usernotifications_created_at_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotifications',
            name='created_at',
        ),
    ]
