# Generated by Django 4.2.5 on 2024-03-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_usernotifications_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='forgot_password_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
