# Generated by Django 4.2.5 on 2024-03-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_userprofile_forgot_password_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='forgot_password_code',
            field=models.CharField(blank=True, default='', editable=False, max_length=6),
        ),
    ]
