# Generated by Django 4.2.5 on 2024-03-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_userprofile_forgot_password_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notifications_total',
            field=models.IntegerField(default=0, editable=False, verbose_name='Notificações não Vistas'),
        ),
    ]
