# Generated by Django 4.2.5 on 2024-04-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_userprofile_notifications_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(default='', null=True, verbose_name='Biografia'),
        ),
    ]
