# Generated by Django 4.2.5 on 2024-04-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_userprofile_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Biografia'),
        ),
    ]
