# Generated by Django 4.2.5 on 2024-04-08 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0035_alter_userprofile_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IMC')),
                ('protein_intake', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Proteína Recomendada (g)')),
                ('water_intake', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Aguá Recomendada (ml)')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Health',
                'verbose_name_plural': 'Health',
            },
        ),
    ]
