# Generated by Django 4.2.5 on 2024-04-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_userhealth_height_alter_userhealth_imc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealth',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='userhealth',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
    ]
