# Generated by Django 4.2.5 on 2024-04-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_userhealth_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealth',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altura (cm)'),
        ),
    ]
