# Generated by Django 4.2.5 on 2024-04-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_userhealth_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealth',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='userhealth',
            name='protein_intake',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Proteína Recomendada (g)'),
        ),
        migrations.AlterField(
            model_name='userhealth',
            name='water_intake',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aguá Recomendada (ml)'),
        ),
        migrations.AlterField(
            model_name='userhealth',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso (kg)'),
        ),
    ]
