# Generated by Django 4.2.5 on 2024-04-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_userhealth_is_valid_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealth',
            name='is_valid_data',
            field=models.BooleanField(default=False, editable=False, verbose_name='Dados estão Válidos'),
        ),
    ]
