# Generated by Django 4.2.5 on 2024-04-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_userhealth_is_valid_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
    ]
