# Generated by Django 4.2.5 on 2024-04-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_userhealthchartdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhealthchartdata',
            options={'ordering': ['-created_at']},
        ),
    ]
