# Generated by Django 4.2.5 on 2024-04-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_userhealthchartdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthchartdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userhealth'),
        ),
    ]
