# Generated by Django 5.1 on 2024-10-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_userfollows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollows',
            options={'verbose_name': 'Seguidor', 'verbose_name_plural': 'Seguidores'},
        ),
    ]
