# Generated by Django 5.1 on 2024-11-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_userfollows_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='biography',
        ),
    ]
