# Generated by Django 5.1 on 2024-11-11 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_remove_userprofile_biography'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkouts',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, default='', related_name='workout_favorited_by', to=settings.AUTH_USER_MODEL, verbose_name='Favoritado por'),
        ),
    ]
