# Generated by Django 4.2.4 on 2023-09-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_categories_name_alter_exercises_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='exercises/%Y/%m/%d/', verbose_name='Imagem / Gif'),
        ),
    ]
