# Generated by Django 4.2.5 on 2023-09-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_exercises_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
