# Generated by Django 4.2.5 on 2023-10-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_exercises_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiMediaImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Nome da Imagem')),
                ('image', models.ImageField(blank=True, default='', upload_to='api/%Y/%m/%d/', verbose_name='Imagem')),
            ],
        ),
    ]
