# Generated by Django 4.2.5 on 2023-10-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_apimediaimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apimediaimages',
            options={'verbose_name': 'Api Explanation Image', 'verbose_name_plural': 'Api Explanation Images'},
        ),
    ]
