# Generated by Django 4.2.5 on 2023-10-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_exercises_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
