# Generated by Django 4.2.5 on 2023-12-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_alter_exercises_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='extra_info',
            field=models.CharField(blank=True, default='', max_length=155, verbose_name='Informações Adicionais'),
        ),
        migrations.AddField(
            model_name='exercises',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Rejeitado'),
        ),
    ]
