# Generated by Django 4.2.5 on 2023-12-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_exercises_extra_info_exercises_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='extra_info',
            field=models.CharField(blank=True, default='', max_length=155, verbose_name='Informações Adicionais (em caso de rejeição)'),
        ),
    ]
