# Generated by Django 4.2.5 on 2023-12-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_alter_exercises_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='extra_info',
            field=models.TextField(blank=True, default='', verbose_name='Informações Adicionais (em caso de rejeição)'),
        ),
    ]
