# Generated by Django 4.2.5 on 2023-12-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_alter_exercises_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
