# Generated by Django 4.2.5 on 2023-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_exercises_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
    ]
