# Generated by Django 4.2.5 on 2023-12-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_alter_exercises_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='was_rejected',
            field=models.BooleanField(default=False, verbose_name='Já foi Rejeitado Antes'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Rejeitar'),
        ),
    ]
