# Generated by Django 4.2.5 on 2024-03-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_alter_exercises_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='extra_info',
            field=models.TextField(blank=True, default='', verbose_name='Informações Adicionais de Rejeição'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='is_published',
            field=models.CharField(choices=[('MYSELF', 'Somente Eu'), ('FOLLOWERS', 'Meus Seguidores'), ('ALL', 'Todos os Usuários')], default='MYSELF', max_length=9),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Rejeitar Exercício'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='was_rejected',
            field=models.BooleanField(default=False, verbose_name='Exercício Rejeitado'),
        ),
    ]
