# Generated by Django 4.2.5 on 2024-03-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_alter_exercises_extra_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='shared_status',
            field=models.CharField(choices=[('MYSELF', 'Somente Eu'), ('FOLLOWERS', 'Meus Seguidores'), ('ALL', 'Todos os Usuários')], default='MYSELF', max_length=9, verbose_name='Status de Compartilhamento'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
