# Generated by Django 4.2.5 on 2024-03-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_exercises_shared_status_alter_exercises_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='shared_status',
            field=models.CharField(choices=[('MYSELF', 'Somente Você'), ('FOLLOWERS', 'Seguidores'), ('ALL', 'Todos os Usuários')], default='MYSELF', max_length=9, verbose_name='Status de Compartilhamento'),
        ),
    ]
