# Generated by Django 4.2.5 on 2024-03-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_alter_exercises_shared_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publicar Exercício'),
        ),
    ]
