# Generated by Django 4.2.5 on 2024-03-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_alter_exercises_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Rejeitar Exercício'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='was_rejected',
            field=models.BooleanField(default=False, verbose_name='Exercício Está Rejeitado'),
        ),
    ]
