# Generated by Django 4.2.5 on 2024-03-20 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0025_alter_exercises_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='favorited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by_users', to=settings.AUTH_USER_MODEL, verbose_name='Favoritado por'),
        ),
    ]
