# Generated by Django 4.2.5 on 2024-03-20 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0026_exercises_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='exercises',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, default='', related_name='favorited_by_users', to=settings.AUTH_USER_MODEL, verbose_name='Favoritado por'),
        ),
    ]
