# Generated by Django 4.2.5 on 2024-03-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0027_remove_exercises_favorited_by_exercises_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Exercício Está Publicado'),
        ),
    ]
