# Generated by Django 4.2.5 on 2024-04-04 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0032_alter_exercises_favorites_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Publicado por'),
        ),
    ]
